# Change these first
owner: unkownY 
repo: lazy-status

sites:
  - name: lazy-people
    url: https://lazy-people.com
    icon: https://lazy-people.com/favicon.ico


status-website:
  # cname: demo.upptime.js.org
  name: lazy-status
  baseUrl: /status-page
  logoUrl: https://lazy-people.com/favicon.ico
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
